# This is free and unencumbered software released into the public domain.

FROM registry.opensuse.org/opensuse/distrobox:latest

# Import RPM keys.
RUN rpm --import https://rpm.releases.hashicorp.com/gpg
RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc

# Configure RPM repos.
COPY hashicorp.repo /etc/zypp/repos.d/repo-hashicorp.repo
COPY microsoft.repo /etc/zypp/repos.d/repo-microsoft.repo
COPY vscode.repo /etc/zypp/repos.d/repo-vscode.repo

# Install packages.
RUN zypper --non-interactive install --no-recommends \
	ansible \
	azure-cli \
	dotnet-sdk-7.0 \
	git \
	hadolint \
	ImageMagick \
	jetbrains-mono-fonts \
	just \
	jq \
	libgthread-2_0-0 \
	libXtst6 \
	npm \
	python3-rpm \
	python3-yamllint \
	ShellCheck \
	terraform \
	&& zypper clean

# Revert configuration changes in base image.
RUN sed -i 's/.*solver.onlyRequires.*/solver.onlyRequires = true/g' /etc/zypp/zypp.conf \
	&& sed -i 's/.*rpm.install.excludedocs.*/rpm.install.excludedocs = yes/g' /etc/zypp/zypp.conf

# Install Azure Artifacts credential provider.
RUN mkdir /opt/nuget \
	&& wget -O- \
	https://github.com/microsoft/artifacts-credprovider/releases/latest/download/Microsoft.Net6.NuGet.CredentialProvider.tar.gz \
	| tar --directory /opt/nuget --extract --gzip

# Copy configuration files.
COPY git.conf /etc/gitconfig
COPY config.vim /etc/vimrc
COPY vscode-keybindings.jsonc /opt/code/data/User/keybindings.json
COPY vscode-settings.jsonc /opt/code/data/User/settings.json

# Copy desktop files
COPY pycharm.desktop /opt/desktop/pycharm.desktop
COPY rider.desktop /opt/desktop/rider.desktop
COPY vscode.desktop /opt/desktop/vscode.desktop

# Setup podman access
COPY host-exec.sh /usr/local/bin/podman
RUN chmod +x /usr/local/bin/podman

# Set default environment variables.
ENV DOTNET_CLI_TELEMETRY_OPTOUT true
ENV NUGET_PLUGIN_PATHS /opt/nuget/plugins/netcore/CredentialProvider.Microsoft/CredentialProvider.Microsoft.dll

# Run script on startup.
COPY init.service /etc/systemd/system/init.service
COPY init.sh /opt/init.sh
RUN chmod +x /opt/init.sh && systemctl enable init
