# This is free and unencumbered software released into the public domain.

name: pc

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 2 * * 0
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      packages: write
    with:
      name: pc
